# Generated by Django 5.0.3 on 2024-04-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_shop_app', '0002_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='importe',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='internal_shop_app.producto'),
        ),
    ]
